# Exported from Render on 2025-01-14T02:22:29Z
services:
- type: web
  name: ejemplo-1
  runtime: python
  repo: https://github.com/S3-Omar/ejemplo
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn main:app
- type: web
  name: ejemplo
  runtime: python
  repo: https://github.com/S3-Omar/ejemplo
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 api.py
version: "1"
